linux = ["sh", "-c", "chmod +x dist/backend/backend && ./dist/backend/backend"]
macos = ["sh", "-c", "chmod +x dist/backend/backend && ./dist/backend/backend"]
windows = ["powershell","-command","./dist/backend/backend.exe"]
